# kubernetes/manifests/cluster-issuer/issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-staging
spec:
  acme:
    email: 1405630484@qq.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-private-key
    solvers:
    - dns01:
        cloudflare:
          email: 1405630484@qq.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            # --- [START OF CORRECTION] ---
            # The 'namespace' field is invalid within this spec for a ClusterIssuer.
            # cert-manager's controller is configured to look for this secret
            # in its own installation namespace ('cert-manager' in our case),
            # which is the correct and expected behavior.
            # namespace: cert-manager # This line is removed.
            # --- [END OF CORRECTION] ---
            key: api-token