# kubernetes/manifests/cluster-issuer/issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    email: 1405630484@qq.com
    # CRITICAL CHANGE: Point to the Let's Encrypt staging server for testing
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-private-key # Use a different secret for staging
    solvers:
    - dns01:
        cloudflare:
          email: 1405630484@qq.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token