# kubernetes/manifests/cluster-issuer/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: "vi7hkPq4FwD5ttV4dvR_IoNVEJSphydRPcT0LVD-" # YOUR_CLOUDFLARE_API_TOKEN