# kubernetes/charts/system/traefik.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # CORRECTED: Using the new, authoritative repository URL from official documentation.
    repoURL: 'https://traefik.github.io/charts'
    chart: traefik
    # UPDATED: No version specified to pull the latest stable version from the repo.
    # For production, pinning to a specific version like '28.0.0' is recommended.
    targetRevision: 37.0.0
    helm:
      values: |
        # The default service type in the modern Traefik chart is already LoadBalancer.
        # Explicitly setting it ensures this behavior regardless of chart defaults.
        service:
          type: LoadBalancer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true