# kubernetes/applications/manifests.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GgYu01/personal-cluster.git
    targetRevision: HEAD
    # This app now manages EVERYTHING under the manifests directory.
    path: kubernetes/manifests
    # Enable recursive scanning
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    # The namespace here is a default, but resources define their own.
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true