# kubernetes/applications/traefik.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 37.0.0
    helm:
      releaseName: traefik
      valuesObject:
        # Deploy as a DaemonSet to run on every node.
        deployment:
          kind: DaemonSet
        
        # Use the host's network stack to bind to ports 80/443 directly.
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet

        ports:
          web:
            port: 80
          websecure:
            port: 443
            tls:
              enabled: true

        # Grant the capability to bind to privileged ports (< 1024).
        securityContext:
          capabilities:
            add: ["NET_BIND_SERVICE"]
        
        # This is a headless service, as Traefik is exposed directly via host ports.
        service:
          type: ClusterIP
          spec:
            clusterIP: None

        # --- HELM CHART FIX ---
        # LOGIC: When using hostNetwork, the default 'RollingUpdate' strategy can cause port conflicts
        # during updates on a single node. 'OnDelete' is a safer strategy for DaemonSets in this mode,
        # requiring manual pod deletion to trigger an update.
        updateStrategy:
          type: OnDelete

        # Allow Traefik to run on the control-plane node.
        tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        
        # Enable Kubernetes CRD provider for IngressRoutes.
        providers:
          kubernetesCRD:
            enabled: true
            allowEmptyServices: true
        
        # Enable RBAC for Traefik.
        rbac:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true