apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "37.0.0" # Lock to a specific stable version
    helm:
      releaseName: traefik
      valuesObject:
        deployment:
          kind: DaemonSet
          # --- STABILITY FIX V16.0 ---
          # Setting hostPID can resolve certain kernel/cgroup interaction issues.
          hostPID: true
        service:
          type: ClusterIP
          spec:
            clusterIP: None # Creates a headless service
        providers:
          kubernetesCRD:
            enabled: true
            allowEmptyServices: true
        rbac:
          enabled: true
        ports:
          web:
            port: 80
            hostPort: 80
          websecure:
            port: 443
            hostPort: 443
            tls:
              enabled: true
        # Allow Traefik to run on the control-plane node
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
        # Required for binding to privileged ports (80, 443)
        securityContext:
          capabilities:
            add:
              - NET_BIND_SERVICE
        # Use Host network to directly expose ports
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        updateStrategy:
          type: OnDelete # A safe update strategy for DaemonSets
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true