# kubernetes/applications/traefik.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 37.0.0
    helm:
      releaseName: traefik
      valuesObject:
        # --- START OF MODIFICATIONS ---
        deployment:
          kind: DaemonSet
        # The updateStrategy should be at the top level of the values,
        # not nested under 'deployment' for many charts.
        updateStrategy:
          type: OnDelete
        # --- END OF MODIFICATIONS ---

        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
          runAsUser: 0
          runAsGroup: 0
          privileged: true

        ports:
          web:
            hostPort: 80
            port: 80
          websecure:
            hostPort: 443
            port: 443
            tls:
              enabled: true
        
        providers:
          kubernetesCRD:
            enabled: true
            allowEmptyServices: true 
        
        rbac:
          enabled: true
        
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
        
        service:
          enabled: false

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true