# kubernetes/applications/traefik.yaml (FINAL & CORRECTED VERSION v6.0)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 37.0.0
    helm:
      releaseName: traefik
      valuesObject:
        # --- Deployment Model ---
        deployment:
          kind: DaemonSet

        # --- Host Network Integration ---
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet

        # --- Port Definitions for hostNetwork mode ---
        ports:
          web:
            port: 80
          websecure:
            port: 443
            tls:
              enabled: true

        securityContext:
          capabilities:
            add: ["NET_BIND_SERVICE"]

        # --- Service for Internal Discovery ---
        service:
          type: ClusterIP
          spec:
            clusterIP: None # Headless Service

        # --- THE DECISIVE FIX FOR THE HELM TEMPLATE ERROR ---
        # LOGIC: The Traefik Helm chart has a validation check: when hostNetwork is true,
        # the rolling update strategy's maxUnavailable cannot be 1 (the default) because
        # it would cause port conflicts during updates. We must specify a compatible
        # update strategy. 'OnDelete' is the simplest and safest for a DaemonSet
        # in this scenario, preventing automatic rollouts and port conflicts.
        updateStrategy:
          type: OnDelete

        # --- RBAC, Providers, and Tolerations (Unchanged) ---
        rbac:
          enabled: true
        providers:
          kubernetesCRD:
            enabled: true
        tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true