# kubernetes/core-services/cert-manager.yaml (Definitive Final Version v5)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10" # Deploy first
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        
        global:
          logLevel: 2 
        
        prometheus:
          enabled: false

        # --- START: CRITICAL FIX FOR TRAEFIK & INGRESSROUTE INTEGRATION ---

        # 1. Enable the feature gate for Gateway API support in the controller.
        extraArgs:
          - --feature-gates=ExperimentalGatewayAPISupport=true
        
        # 2. CRITICAL: Explicitly enable the 'gateway-shim' controller itself.
        # This controller is disabled by default and is required to process Gateway API
        # resources, which includes Traefik's IngressRoutes.
        gateway-shim:
          enabled: true

        # The 'ingress-shim' can remain configured for default behavior.
        ingressShim:
          defaultIssuerName: cloudflare
          defaultIssuerKind: ClusterIssuer
          defaultIssuerGroup: cert-manager.io
          
        # --- END: CRITICAL FIX FOR TRAEFIK & INGRESSROUTE INTEGRATION ---

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true