# kubernetes/core-services/cert-manager.yaml (Definitive Final Version)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        # 不需要任何特殊的 extraArgs 或 shim 配置
        # ingress-shim 默认会处理标准的 Ingress 资源
        prometheus:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true