# kubernetes/core-services/cert-manager.yaml (Definitive Final Version)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10" # Deploy first
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
      values: |
        # Install the CRDs as part of this release
        installCRDs: true
        
        # Set log level for debugging purposes
        global:
          logLevel: 2 
        
        # We are not using Prometheus for now
        prometheus:
          enabled: false

        # --- START: CRITICAL FIX FOR TRAEFIK & INGRESSROUTE INTEGRATION ---
        # This is the correct way to pass extra arguments to the cert-manager controller pod.
        # We are telling the ingress-shim controller within cert-manager to specifically
        # look for Ingress-like objects that have the 'ingressClassName: traefik' or
        # are associated with the Traefik controller. This is the key to enable
        # processing of IngressRoute resources.
        extraArgs:
          - --feature-gates=ExperimentalGatewayAPISupport=true
        
        # The 'ingress-shim' configuration is still relevant.
        ingressShim:
          defaultIssuerName: cloudflare
          defaultIssuerKind: ClusterIssuer
          defaultIssuerGroup: cert-manager.io
        # --- END: CRITICAL FIX FOR TRAEFIK & INGRESSROUTE INTEGRATION ---

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true