# kubernetes/core-services/cert-manager.yaml (Definitive Final Version v6)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10" # Deploy first
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        
        global:
          logLevel: 2 
        
        prometheus:
          enabled: false

        # --- START: CRITICAL FIX FOR TRAEFIK & INGRESSROUTE INTEGRATION (v6) ---
        # This is the most robust method: controlling everything via command-line arguments.
        # It avoids inconsistencies between different chart versions' values.yaml structure.
        extraArgs:
          # 1. Enable the feature gate for Gateway API support
          - --feature-gates=ExperimentalGatewayAPISupport=true
          
          # 2. CRITICAL: Explicitly define which controllers to enable.
          # By providing this list, we override the chart's default list of controllers.
          # We ensure 'gateway-shim' is included.
          - --controllers=certificates-issuing,certificates-key-manager,certificates-metrics,certificates-readiness,certificates-request-manager,certificates-revision-manager,certificates-trigger,challenges,clusterissuers,issuers,orders,ingress-shim,gateway-shim

        # We no longer need the 'gateway-shim' block as we control it via extraArgs.
        # --- END: CRITICAL FIX FOR TRAEFIK & INGRESSROUTE INTEGRATION (v6) ---

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true