# kubernetes/core-services/traefik.yaml (Definitive Final Version v17)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://traefik.github.io/charts'
    chart: traefik
    targetRevision: 37.0.0
    helm:
      values: |
        # Use LoadBalancer, the K3s-native way to expose services.
        service:
          enabled: true
          type: LoadBalancer
        
        # We do not need HostPorts anymore.
        ports:
          web:
            port: 8000
          websecure:
            port: 8443
            tls:
              enabled: true
        
        # Standard providers and IngressClass setup
        providers:
          kubernetesIngress:
            enabled: true
        ingressClass:
          enabled: true
          isDefaultClass: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true