# kubernetes/core-services/traefik.yaml (Definitive Final Version)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://traefik.github.io/charts'
    chart: traefik
    targetRevision: 37.0.0 # Pinning version for stability
    helm:
      values: |
        # 明确创建名为 'traefik' 的 IngressClass 资源
        ingressClass:
          enabled: true
          isDefaultClass: true # 将其设为集群默认
        
        # 启用 provider 来监听标准的 Ingress 资源
        providers:
          kubernetesIngress:
            enabled: true
            allowCrossNamespace: true
          # 我们仍然可以保留 CRD provider，以备将来使用
          kubernetesCRD:
            enabled: true
            allowAllNamespaces: true
        
        # 定义入口点
        ports:
          web:
            port: 8000
            # 建议：可以添加重定向到 HTTPS
            # redirectTo: websecure
          websecure:
            port: 8443
            tls:
              enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true