# kubernetes/core-services/traefik.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://traefik.github.io/charts'
    chart: traefik
    targetRevision: 37.0.0 # <--- 请确认此版本是否正确，或使用最新版
    helm:
      values: |
        # 启用 dashboard，但默认不创建 IngressRoute
        dashboard:
          enabled: true
        
        # 在 providers.kubernetesCRD 中定义入口点
        # 这告诉 Traefik 它应该监听哪些端口
        ports:
          web:
            port: 8000
          websecure:
            port: 8443
            tls:
              enabled: true

        # 允许所有命名空间的 IngressRoute
        providers:
          kubernetesCRD:
            allowAllNamespaces: true
          # kubernetesIngress 也可以保留，以防万一
          kubernetesIngress:
            allowCrossNamespace: true
        
        # 禁用默认的 IngressClass，因为我们将手动管理
        ingressClass:
          enabled: false
        
        # 禁用 IngressRoute for dashboard，我们将手动创建
        ingressRoute:
          dashboard:
            enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
# --- REMOVE THE ENTIRE 'hooks' SECTION FROM HERE ---