# kubernetes/core-services/traefik.yaml (Definitive Final Version v16)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://traefik.github.io/charts'
    chart: traefik
    targetRevision: 37.0.0
    helm:
      values: |
        # CRITICAL CHANGE: Disable the Service entirely.
        # We will expose Traefik directly via HostPorts on the Deployment.
        service:
          enabled: false

        # CRITICAL CHANGE: Define HostPorts directly on the Deployment.
        # This creates the most direct path from the host to the Traefik pod, bypassing svclb.
        ports:
          web:
            port: 8000
            hostPort: 80
            protocol: TCP
          websecure:
            port: 8443
            hostPort: 443
            protocol: TCP
            tls:
              enabled: true
        
        # Enable providers for standard Ingress
        providers:
          kubernetesIngress:
            enabled: true
          kubernetesCRD:
            enabled: true # Keep this for future flexibility

        # Create the default IngressClass
        ingressClass:
          enabled: true
          isDefaultClass: true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true