# Code Analysis: Exposes the Authentik service via Traefik, following your existing pattern.
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-https
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.core01.prod.gglohh.top`)
      kind: Rule
      services:
        # The Authentik helm chart creates a service named 'authentik-server'
        - name: authentik-server
          port: http
  tls:
    secretName: authentik-tls-staging