# File: kubernetes/manifests/authentik-ingress/ingress.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata: 
  name: authentik-https
  namespace: authentik
spec: 
  entryPoints: 
    - websecure
  routes: 
    - kind: Rule
      match: Host(`auth.core01.prod.gglohh.top`)          # clean, no hidden chars
      services: 
        - name: authentik-server
          port: 80                                        # numeric port to avoid ambiguity
          passHostHeader: true
  tls: 
    secretName: authentik-tls-staging