# kubernetes/apps-of-apps/0-core-services.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-services
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/GgYu01/personal-cluster.git
    targetRevision: HEAD
    path: kubernetes/core-services
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # This app itself creates other apps in other namespaces
  syncPolicy:
    automated:
      prune: true
      selfHeal: true