# kubernetes/manifests/frps/config.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: frps-ui-config
  namespace: frp-system
data:
  frps.toml: |
    # --- Core bind (UI) ---
    bindPort = 7001

    # --- Auth (simple) ---
    [auth]
    method = "token"
    token = "password"

    # --- Subdomain host for HTTP vhosts ---
    subdomainHost = "core01.prod.gglohh.top"

    # --- HTTP vhost for browser side (TLS by Traefik) ---
    vhostHTTPPort = 8080

    # --- Web dashboard (UI) ---
    [webServer]
    addr = "0.0.0.0"
    port = 7500
    user = "admin"
    password = "password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frps-ws-config
  namespace: frp-system
data:
  frps.toml: |
    # --- Core bind (WS) ---
    bindPort = 7002

    # --- Auth (simple) ---
    [auth]
    method = "token"
    token = "password"

    # --- Subdomain host for HTTP vhosts ---
    subdomainHost = "core01.prod.gglohh.top"

    # --- HTTP vhost for WS side (TLS by Traefik) ---
    vhostHTTPPort = 8081

    # --- Web dashboard (WS) ---
    [webServer]
    addr = "0.0.0.0"
    port = 7501
    user = "admin"
    password = "password"