# kubernetes/manifests/frps/service-and-routes.yaml
apiVersion: v1
kind: Service
metadata:
  name: frps-service
  namespace: frp-system
spec:
  selector:
    app: frps
  ports:
  - name: frps-bind
    port: 7000
  - name: vhost-http
    port: 8080
  - name: dashboard
    port: 7500
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: frps-tcp-ingress
  namespace: frp-system
spec:
  entryPoints:
    - frps  # must exist in Traefik static config; deploy.sh will ensure it
  routes:
  - match: HostSNI(`*`)
    services:
    - name: frps-service
      port: 7000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frps-http-ingress
  namespace: frp-system
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`{subdomain:.+}.core01.prod.gglohh.top`)
    services:
    - name: frps-service
      port: 8080
  tls:
    secretName: wildcard-core01-prod-gglohh-top-tls