# kubernetes/apps/authentik-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: authentik
  namespace: argocd
  annotations: 
    argocd.argoproj.io/sync-wave: "10"
spec: 
  project: default
  source: 
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2025.8.4
    helm: 
      releaseName: authentik
      values: |
        # ========= Authentik core =========
        authentik:
          secret_key: "a_very_long_and_random_secret_key_change_me"
          error_reporting:
            enabled: false
          # [ADD] Wire application DB password to embedded PostgreSQL
          postgresql:
            password: "a_strong_database_password_change_me"

        # ========= PostgreSQL (embedded) =========
        postgresql:
          enabled: true
          auth:
            password: "a_strong_database_password_change_me"

        # ========= Redis (embedded) =========
        redis:
          enabled: true
          auth:
            enabled: false
  destination: 
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy: 
    automated: 
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true