# kubernetes/apps/authentik-app.yaml
# Code Analysis: Deploys Authentik using its official Helm chart, following the same
# pattern as your existing n8n-app.yaml. A sync-wave of "10" ensures it deploys
# after frps and other core services.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2024.6.1 # Pin chart version for stability
    helm:
      releaseName: authentik
      values: |
        # IMPORTANT: Replace with a long random string
        authentik:
          secret_key: "a_very_long_and_random_secret_key_change_me"

        # For simplicity, enable the bundled PostgreSQL and Redis
        postgresql:
          enabled: true
          auth:
            # IMPORTANT: Replace with a strong password
            password: "a_strong_database_password_change_me"

        redis:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true