# File: kubernetes/apps/cert-manager-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.18.2
    helm:
      releaseName: cert-manager
      values: |
        crds:
          enabled: true

        startupapicheck:
          enabled: true
          timeout: 5m

        prometheus:
          enabled: false

        # Limit controller/webhook/cainjector resources
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi

        webhook:
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi

        cainjector:
          resources:
            requests:
              cpu: 30m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true