# kubernetes/apps/n8n-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: n8n
    targetRevision: 1.15.4
    helm:
      releaseName: n8n
      values: |
        # ======================================================================
        # n8n Core Configuration
        # ======================================================================
        encryptionKey: "a-very-insecure-but-static-encryption-key-for-n8n"
        timezone: "Asia/Shanghai"

        # 主容器设置（注意：此 chart 版本不支持 startupProbe / extraEnv）
        main:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 500m
              memory: 512Mi

          # 该 chart 支持 livenessProbe/readinessProbe
          livenessProbe:
            enabled: true
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12

          readinessProbe:
            enabled: true
            httpGet:
              path: /healthz/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12

          # 环境变量扩展：使用 extraEnvVars（而不是 extraEnv）
          extraEnvVars:
            - name: N8N_HOST
              value: n8n.core01.prod.gglohh.top
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: N8N_PROTOCOL
              value: https
            - name: N8N_PORT
              value: "5678"
            - name: WEBHOOK_URL
              value: https://n8n.core01.prod.gglohh.top/

        # 二进制数据本地持久化
        binaryData:
          mode: "filesystem"

        # 执行模式：队列 + 1 个 worker
        worker:
          mode: queue
          count: 1

        # 数据库：PostgreSQL 子图表
        db:
          type: postgresdb

        postgresql:
          enabled: true
          architecture: standalone
          auth:
            database: "n8n"
            username: "admin"
            password: "password"
          primary:
            persistence:
              enabled: true
              storageClass: "local-path"
              size: 8Gi

        # 队列：Redis 子图表
        redis:
          enabled: true
          architecture: standalone
          auth:
            enabled: true
            password: "password"
          master:
            persistence:
              enabled: true
              storageClass: "local-path"
              size: 2Gi

        # Ingress（Traefik）
        ingress:
          enabled: true
          className: "traefik"
          hosts:
            - host: n8n.core01.prod.gglohh.top
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: n8n-tls-staging
              hosts:
                - n8n.core01.prod.gglohh.top

  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true