apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: argocd-server-tls-staging
  issuerRef:
    name: cloudflare-staging
    kind: ClusterIssuer
  dnsNames:
  - argocd.core01.prod.gglohh.top